name: authentication
description: "a repository that deals with authentication"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_annotation:
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
